name: Mehant Build

on:
  workflow_dispatch: {}

jobs:

  image_build:
    name: Image build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: info
        uses: konveyor/get-env-info@v1
      - id: image_tag
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          if [ "$BRANCH" == 'main' ] ; then
            echo "::set-output name=tag::latest"
          else
            echo "::set-output name=tag::$BRANCH"
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - run: echo "${{ secrets.DOCKER_PASS }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build multi arch image
        run: VERSION='${{ steps.image_tag.outputs.tag }}' GO_VERSION='${{ steps.info.outputs.go_version }}' make cbuild
